// libs/create-deepagent/registry/frameworks/next/components/Chat.tsx
"use client";

import { useEffect, useRef, useState } from "react";

import { HumanMessage } from "@langchain/core/messages";
import { useStreamContext } from "@langchain/react";

import type { Agent } from "@/lib/agent";
import { Conversation } from "./Conversation";
import { SubagentDetail } from "./Subagents";

const EXAMPLE_PROMPT =
  "Research LangGraph streaming, and separately calculate 42 * 17.";

export function Chat({
  onRunSettled,
}: {
  threadId: string;
  /** Called when a run settles, so the sidebar can refresh titles/order. */
  onRunSettled: () => void;
}) {
  const stream = useStreamContext<Agent>();
  const [content, setContent] = useState(EXAMPLE_PROMPT);
  const [openSubagentId, setOpenSubagentId] = useState<string | null>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  // Refresh the sidebar whenever a run finishes (titles derive from the first
  // message; order from the latest checkpoint, both owned by the server).
  useEffect(() => {
    if (!stream.isLoading) onRunSettled();
  }, [stream.isLoading, onRunSettled]);

  function autoGrow() {
    const node = textareaRef.current;
    if (!node) return;
    node.style.height = "auto";
    node.style.height = `${Math.min(node.scrollHeight, 200)}px`;
  }

  const subagents = [...stream.subagents.values()];
  const openSubagent = openSubagentId
    ? subagents.find((snapshot) => snapshot.id === openSubagentId)
    : undefined;

  function handleSubmit() {
    const nextContent = content.trim();
    if (nextContent.length === 0 || stream.isLoading) return;

    setContent("");
    if (textareaRef.current) textareaRef.current.style.height = "auto";
    void stream.submit({
      messages: [new HumanMessage(nextContent)],
    });
  }

  // Subagent detail view: breadcrumb + that subagent's chat (no composer).
  if (openSubagent) {
    return (
      <main className="chat-main">
        <nav aria-label="Breadcrumb" className="breadcrumb">
          <button
            className="crumb-link"
            onClick={() => setOpenSubagentId(null)}
            type="button"
          >
            Main chat
          </button>
          <span className="crumb-sep">/</span>
          <span className="crumb-current">{openSubagent.name}</span>
        </nav>
        <div className="conversation">
          <div className="conversation-inner">
            <SubagentDetail snapshot={openSubagent} />
          </div>
        </div>
      </main>
    );
  }

  // Main view: messages + subagent chips, with the composer pinned at the bottom.
  return (
    <main className="chat-main">
      <div className="conversation">
        <div className="conversation-inner">
          <Conversation onOpenSubagent={setOpenSubagentId} />
        </div>
      </div>

      <div className="composer-bar">
        <form
          className="composer"
          onSubmit={(event) => {
            event.preventDefault();
            handleSubmit();
          }}
        >
          <textarea
            aria-label="Message"
            onChange={(event) => {
              setContent(event.target.value);
              autoGrow();
            }}
            onKeyDown={(event) => {
              if (event.key === "Enter" && !event.shiftKey) {
                event.preventDefault();
                handleSubmit();
              }
            }}
            placeholder="Ask for research, a calculation, or both..."
            ref={textareaRef}
            rows={1}
            value={content}
          />
          <button
            disabled={content.trim() === "" || stream.isLoading}
            type="submit"
          >
            Send
          </button>
        </form>
      </div>
    </main>
  );
}

// libs/create-deepagent/registry/frameworks/nuxt/app/components/Chat.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { HumanMessage } from "@langchain/core/messages";
import { useStreamContext } from "@langchain/vue";

import MessageList from "./MessageList.vue";
import SubagentDetail from "./SubagentDetail.vue";

const EXAMPLE_PROMPT =
  "Research LangGraph streaming, and separately calculate 42 * 17.";

const emit = defineEmits<{ runSettled: [] }>();

const stream = useStreamContext();

// Refresh the sidebar whenever a run finishes (titles derive from the first
// message; order from the latest checkpoint, both owned by the server).
watch(
  () => stream.isLoading.value,
  (loading) => {
    if (!loading) emit("runSettled");
  },
);

const content = ref(EXAMPLE_PROMPT);
const openSubagentId = ref<string | null>(null);
const textareaRef = ref<HTMLTextAreaElement | null>(null);

const subagents = computed(() => [...stream.subagents.value.values()]);
const openSubagent = computed(() =>
  openSubagentId.value
    ? subagents.value.find((snapshot) => snapshot.id === openSubagentId.value)
    : undefined,
);

function autoGrow() {
  const node = textareaRef.value;
  if (!node) return;
  node.style.height = "auto";
  node.style.height = `${Math.min(node.scrollHeight, 200)}px`;
}

function handleSubmit() {
  const nextContent = content.value.trim();
  if (nextContent.length === 0 || stream.isLoading.value) return;

  content.value = "";
  if (textareaRef.value) textareaRef.value.style.height = "auto";
  void stream.submit({ messages: [new HumanMessage(nextContent)] });
}

function handleKeydown(event: KeyboardEvent) {
  if (event.key === "Enter" && !event.shiftKey) {
    event.preventDefault();
    handleSubmit();
  }
}
</script>

<template>
  <!-- Subagent detail view: breadcrumb + that subagent's chat (no composer). -->
  <main v-if="openSubagent" class="chat-main">
    <nav aria-label="Breadcrumb" class="breadcrumb">
      <button class="crumb-link" type="button" @click="openSubagentId = null">
        Main chat
      </button>
      <span class="crumb-sep">/</span>
      <span class="crumb-current">{{ openSubagent.name }}</span>
    </nav>
    <div class="conversation">
      <div class="conversation-inner">
        <SubagentDetail :snapshot="openSubagent" />
      </div>
    </div>
  </main>

  <!-- Main view: messages + subagent chips, composer pinned at the bottom. -->
  <main v-else class="chat-main">
    <div class="conversation">
      <div class="conversation-inner">
        <MessageList @open-subagent="openSubagentId = $event" />
      </div>
    </div>

    <div class="composer-bar">
      <form class="composer" @submit.prevent="handleSubmit">
        <textarea
          ref="textareaRef"
          v-model="content"
          aria-label="Message"
          placeholder="Ask for research, a calculation, or both..."
          rows="1"
          @input="autoGrow"
          @keydown="handleKeydown"
        />
        <button
          :disabled="content.trim() === '' || stream.isLoading.value"
          type="submit"
        >
          Send
        </button>
      </form>
    </div>
  </main>
</template>
